# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.luks.devices = [
    { name = "enc-root"; device = "/dev/disk/by-uuid/f35f8624-6607-485d-b59e-76f87fd9a888"; }
  ];

  boot.initrd.postMountCommands = ''
    mkdir -p /root-before-bind
    mount --move $targetRoot /root-before-bind
    mount -o bind /root-before-bind/Nix/OS $targetRoot
    umount /root-before-bind
  '';

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/enc-root";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/906e71f3-84a9-4faa-be0a-46594c64a935";
      fsType = "ext4";
    };

  fileSystems."/mnt/gentoo" =
    { device = "/dev/mapper/enc-root";
      fsType = "ext4";
    };

  swapDevices =
    [];

  nix.maxJobs = 4;
}
